### ISSUE TITLE
Is there any reason not to use xnor_gemm in fprop for training?

### ISSUE THREAD

**Issue by s271** [MatthieuCourbariaux/BinaryNet#6]
In training examples xnor_gemm is not used for forward propagation, is there any reason for it?
As I understand convolution in forward propagation during the training use both binary activation and binarized weights, so xnor kernel should work for it too, correct?
Is cudnn theano convolution still faster?

**Comment by MatthieuCourbariaux** [comment]
> In training examples xnor_gemm is not used for forward propagation, is there any reason for it?

There are several reasons we do not use the xnor_gemm kernel for the training forward propagation:
1. The speedup would be small (because the backpropagation still requires full precision)
2. Our kernel has a memory leak.
3. Our kernel does not accept the small batch size we use at train-time.

> As I understand convolution in forward propagation during the training use both binary activation and binarized weights, so xnor kernel should work for it too, correct?

You are correct.

> Is cudnn theano convolution still faster?

Our kernel was faster than Theano CuDNN when we wrote it.
It may no longer be the case.
