### ISSUE TITLE
Binarization of Layer Inputs

### ISSUE THREAD

**Issue by gplhegde** [MatthieuCourbariaux/BinaryNet#9]
Hi,
      I could not see where the activations are binarized in the code. I am looking into code under Train-time directory. Can anyone point me to the code where layer input binarization is happening? Thanks

**Comment by maltanar** [comment]
For intermediate layers (i.e. any layer whose input is produced by a previous convolution/FC layer) the sign function activation of the previous layer would ensure that the data is binarized, but I believe that the very first layer's input (raw image data) is not actually binarized.

Also with regards to the intermediate layer inputs, note that using padding in the convolutional layers can break the binararized input assumption (i.e. the previous layer would produce -1 +1 data only, but the padded version of this would have -1 0 +1 pixels). This could be avoided using the "valid" padding mode, but that may result in lower accuracy since it throws away the edge pixels.

**Comment by gplhegde** [comment]
I see. The binary_sigmoid, binary_tanh, and hard_sigmoid doing that job. Thanks for pointing that out. I think extending the boundary pixels into padding area will keep the input to CONV layer to be +1/-1.
